apiVersion: v1
kind: PersistentVolume
metadata:
  name: valkey-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: host.k3d.internal
    # Path dell'NFS, lo stesso che specifico quando monto
    # con il comando mount (vedi ./nfs/docker-compose.yml)
    path: /
  mountOptions:
    - vers=4
